export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const LOAD_RESULTS_SUCCESS = 'LOAD_RESULTS_SUCCESS';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const REVERT_PAGE_BACK = 'REVERT_PAGE_BACK';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
